### ISSUE TITLE
Design: Need sperate logo for content and draft in dashboard navigation sidebar.

### ISSUE THREAD

**Issue by nlok5923** [Extent-Org/Extent-Frontend#11]
Issue: currently the logo of content and draft are same in the navigation sidebar.
![image](https://user-images.githubusercontent.com/56120084/208962164-21b5e9a2-4327-4b32-adb9-122327d1317c.png)

@solankidivyam PTAL

**Comment by solankidivyam** [comment]
I have updated the logo in the designs @Himanshuiiit please take a look to update in the code.
