### ISSUE TITLE
Img: At footer section netlify deployment not able to resolve logo src

### ISSUE THREAD

**Issue by nlok5923** [Extent-Org/Extent-Frontend#2]
For issue visit homepage for netlify deployment
![image](https://user-images.githubusercontent.com/56120084/208082424-18eac897-1141-4fc9-950a-873d74f9e651.png)

**Comment by nlok5923** [comment]
@darshanhande11 can you look into this also created a task at notion for this.

**Comment by darshanhande11** [comment]
@nlok5923 Yeah sure. Will fix it (Although, it works on localhost, lets see...)
