### ISSUE TITLE
Chore: Logo mismatch on homepage and dashboard

### ISSUE THREAD

**Issue by nlok5923** [Extent-Org/Extent-Frontend#9]
Home page extent logo:
![image](https://user-images.githubusercontent.com/56120084/208834372-aad990de-4c28-4c64-a7a0-308bb32354f3.png)

Dashboard page extent logo:
![image](https://user-images.githubusercontent.com/56120084/208834449-bd026909-c8b4-4e89-85e8-a2fae63126a7.png)

**Comment by nlok5923** [comment]
@darshanhande11 PTAL

**Comment by darshanhande11** [comment]
@nlok5923 I have included this in #15 . @Himanshuiiit would be working on #15 .
